apiVersion: v1
kind: Service
metadata:
  name: demo2-service
  labels:
    app: demo2
spec:
  type: NodePort
  selector:
    app: demo2
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
